on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: create GitHub release
        run: |
          zip -r two-dot-task-js-v${{ steps.get_version.outputs.VERSION }}.zip lib/ jspsych/
          gh release create v${{ steps.get_version.outputs.VERSION }} two-dot-task-js-v${{ steps.get_version.outputs.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
